- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /ect/yum.repos.d/mongodb.repo

- name: install mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  ansible.builtin.shell: mongo --host 172.31.81.10 </app/schema/{{component}}.js