

- name: install nysql client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: load schema
  ansible.builtin.shell: mysql -h 172.31.90.148 -uroot -pRoboShop@1 < /app/schema/{{component}}.sql